### ISSUE TITLE
Color and Style

### ISSUE THREAD

**Issue by violaberg** [violaberg/memo-bubble#10]
As a ***developer*** I can ***choose color palette and style of the app*** so that ***I can have a clear vision of end result***

### Tasks:

- [x] Create color palette once colors have been chosen

- [x] Decide the style of project

- [ ] Choose logo and background to suit the chosen style and colors

**Comment by violaberg** [comment]
_**Primary Colors:**_

_Electric Blue:_ `#1F8EF1`
_Vibrant Purple:_ `#9B51E0`

**_Secondary Colors:_**

_Aqua:_ `#00E5FF`
_Neon Pink:_ `#FF0080`
_Deep Space Blue:_ `#1B1F3B`
_Cyan:_ `#00BFFF`

**_Accent Colors:_**

_Turquoise:_ `#40E0D0`
_Lavender:_ `#E6E6FA`

**_Neutral Colors:_**

_Dark Charcoal:_  `#333333`
_Light Gray:_  `#D3D3D3`
_White Smoke:_ ` #F5F5F5`

_Example Usage_

_Background:_ Deep Space Blue `#1B1F3B`
_Primary Buttons and Links:_ Electric Blue `#1F8EF1`
_Secondary Buttons:_ Vibrant Purple `#9B51E0`
_Highlights and Active States:_ Neon Pink `#FF0080`
_Cards and Panels:_ Dark Charcoal `#333333` with accents of Light Gray `#D3D3D3`
_Primary Text:_ White Smoke `#F5F5F5`
_Secondary text:_ Light Gray `#D3D3D3`

**Comment by violaberg** [comment]
![Image](https://github.com/violaberg/memo-bubble/assets/136760923/a6579d94-ca2b-4524-b759-5fe5a3c36f0d)
