### ISSUE TITLE
Likes

### ISSUE THREAD

**Issue by violaberg** [violaberg/memo-bubble#105]
As a ***user*** I can ***like a capsule*** so that ***I can contribute to community***

### Acceptance criteria:

1.  User can click on like button 'heart' on individual capsule page.

2. Like count updates dynamically and is visible instantly.

### Tasks:

- [x] Implement the likes component on the frontend.
- [ ] Find suitable Fontawesome icon and adjust styling to suit Memo Bubble.

- [ ] Display likes count dynamically.
- [ ] Save likes to capsule.
