### ISSUE TITLE
Capsule comments

### ISSUE THREAD

**Issue by violaberg** [violaberg/memo-bubble#106]
As a ***logged-in user*** I can ***add a comment to individual capsule*** so that ***so that I can contribute my thoughts to community***

### Acceptance criteria:

1. Easy to use comment form

2. Comments added instantly

3. Error message if user is not logged-in and link to Sign in page

### Tasks:

- [x] Create comments component

- [x] Style to suit Memo Bubble app

- [ ] Ensure only logged-in users can leave comments
