### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by violaberg** [violaberg/memo-bubble#11]
As a ***developer*** I can ***choose fonts*** so that ***I can create an appealing app***

### Tasks:

- [x] Find Google fonts that complement the chosen style for project

- [x] Ensure text is easy to read using chosen fonts

- [x] Add to project

**Comment by violaberg** [comment]
![Image](https://github.com/violaberg/memo-bubble/assets/136760923/d26b1a16-f515-49a4-961c-b50f08bbf304)
![Image](https://github.com/violaberg/memo-bubble/assets/136760923/6025599c-0b49-4f49-9f7e-f6e9b789ca38)
