### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by violaberg** [violaberg/memo-bubble#22]
As a ***user*** I can ***view an About page*** so that ***I can learn more about Memo Bubble and the idea behind it***

### Acceptance criteria:

1. When user clicks on the About link in the navigation menu it takes them to the About page

2. Easy to read information about the purpose and vision of Memo Bubble

### Tasks:

- [x] Create About page
- [x] Link it to nav

- [x] Populate with needed information to engage users

- [x] Ensure the page is responsive and visually appealing
