### ISSUE TITLE
Add Location to Time Capsule

### ISSUE THREAD

**Issue by violaberg** [violaberg/memo-bubble#8]
As a ***user*** I can ***add a location to my time capsule*** so that ***the place where it was created is recorded and can be viewed***

### Acceptance criteria:

1. User can add a location when creating a time capsule.

2. The location can be automatically detected using GPS or manually entered.

3. The location is saved and displayed when viewing the time capsule.

### Tasks:

- [ ] Update the time capsule model to include location data.

- [ ] Implement the option to add or automatically detect location in the time capsule creation form on the frontend.

- [ ] Implement the option to add or automatically detect location in the time capsule creation form on the frontend.
